/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    var foobar: String
      get() {
        return this.foobar
      }
      set(str) {
        this.foobar = str
      }
}

fun main() {
  var app = App()
  app.foobar = "Ben"
  println(app.greeting)
  println(app.foobar)
}
